00-golang-task: invalidate iterator test
ADKosm/sd-2021-checker pull request #2
Opened 2022-09-16 16:53 UTC by pdanilov

Add a test for both forward and backward iterators checking an invalidation after partial bypass and sequent collection's modification.

2022-09-16 21:36 UTC, lfyuomr-gylo requested changes

2022-09-16 21:36 UTC, lfyuomr-gylo commented on golang-task/impl_test.go
> +			for _, key := range keys[:limit] {
а зачем здесь копирование вместо просто `expectedOrder := keys[:limit]`

2022-09-16 21:36 UTC, lfyuomr-gylo commented on golang-task/impl_test.go
> +				_, _, err := it.Next()
Этот тест тестирует undefined behaviour!

2022-09-16 21:36 UTC, lfyuomr-gylo commented on golang-task/impl_test.go
> +				_, _, err := it.Next()
В документации к `IterateBy` же написано

> // Any modification of the collection corrupts all the iterators obtained prior the modification.

Т.е. после того, как коллекция модифицирована, итератор ломается. Возможно следует дописать более развернуто, что подразумевается под «ломается» — я имел ввиду, что любое использование итератора приводит к undefined behaviour

2022-09-17 03:35 UTC, pdanilov commented on golang-task/impl_test.go
> +				_, _, err := it.Next()
Ну в go как раз нет ub встроенного так скажем, собственно, что и хорошо
Поэтому я как раз подумал, что было бы неплохо, чтобы протестировать поведение "инвалидация итератора = все последующие вызовы будут возвращать ошибку". Раз это не так, то в принципе MR можно закрывать)

2022-09-17 06:56 UTC, lfyuomr-gylo commented on golang-task/impl_test.go
> +				_, _, err := it.Next()
> инвалидация итератора = все последующие вызовы будут возвращать ошибку

Это сильно усложняет реализацию, поэтому в этой домашке не требуется. И если уж и реализовывать такую фичу, то нужно возвращать отдельную ошибку, которая будет сигнализировать, что коллекция была изменена. По аналогии с тем, как в Java итераторы бросают ConcurrentModificationException

2022-09-17 06:57 UTC, closed without merging